spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sduonline_simulation
    username: root
    password: egg10052005
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0